// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getMockCallLogsSort = z.enum(['servedAt']);

export type GetMockCallLogsSort = z.infer<typeof getMockCallLogsSort>;
