// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const serverResponseLanguage1 = z.enum(['text', 'javascript', 'json', 'html', 'xml']);

export type ServerResponseLanguage1 = z.infer<typeof serverResponseLanguage1>;
