// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getAllElementsAndFoldersType = z.enum(['api', 'folder', 'collection', 'workspace']);

export type GetAllElementsAndFoldersType = z.infer<typeof getAllElementsAndFoldersType>;
