// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getAllElementsAndFoldersSort = z.enum(['createdAt', 'updatedAt']);

export type GetAllElementsAndFoldersSort = z.infer<typeof getAllElementsAndFoldersSort>;
