// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const globalVariableType = z.enum(['default', 'secret']);

export type GlobalVariableType = z.infer<typeof globalVariableType>;
