// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const deleteCollectionFolderData: any = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    owner: z.string().optional(),
  });
});

/**
 * The folder's information.
 * @typedef  {DeleteCollectionFolderData} deleteCollectionFolderData - The folder's information. - The folder's information.
 * @property {string} - The folder's ID.
 * @property {string} - The user ID of the folder's owner.
 */
export type DeleteCollectionFolderData = z.infer<typeof deleteCollectionFolderData>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const deleteCollectionFolderDataResponse: any = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      owner: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      owner: data['owner'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const deleteCollectionFolderDataRequest: any = z.lazy(() => {
  return z.object({ id: z.string().nullish(), owner: z.string().nullish() }).transform((data) => ({
    id: data['id'],
    owner: data['owner'],
  }));
});
