// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getScimGroupResourceMembers = z.lazy(() => {
  return z.object({
    value: z.string().optional(),
    display: z.string().optional(),
  });
});

/**
 *
 * @typedef  {GetScimGroupResourceMembers} getScimGroupResourceMembers
 * @property {string} - The member's SCIM ID.
 * @property {string} - The member's display name.
 */
export type GetScimGroupResourceMembers = z.infer<typeof getScimGroupResourceMembers>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getScimGroupResourceMembersResponse = z.lazy(() => {
  return z
    .object({
      value: z.string().optional(),
      display: z.string().optional(),
    })
    .transform((data) => ({
      value: data['value'],
      display: data['display'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getScimGroupResourceMembersRequest = z.lazy(() => {
  return z.object({ value: z.string().nullish(), display: z.string().nullish() }).transform((data) => ({
    value: data['value'],
    display: data['display'],
  }));
});
