// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const metaResourceType = z.enum(['User']);

export type MetaResourceType = z.infer<typeof metaResourceType>;
