// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { operationsOp2 } from './operations-op-2';
import { operationsValue2, operationsValue2Request, operationsValue2Response } from './operations-value-2';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateScimUserStateOperations = z.object({
  op: operationsOp2.optional(),
  value: operationsValue2.optional(),
});

/**
 *
 * @typedef  {UpdateScimUserStateOperations} updateScimUserStateOperations
 * @property {OperationsOp2} - The operation to perform.
 * @property {OperationsValue2} - The performed operation's value.
 */
export type UpdateScimUserStateOperations = z.infer<typeof updateScimUserStateOperations>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateScimUserStateOperationsResponse = z
  .object({
    op: operationsOp2.optional(),
    value: operationsValue2Response.optional(),
  })
  .transform((data) => ({
    op: data['op'],
    value: data['value'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateScimUserStateOperationsRequest = z
  .object({ op: operationsOp2.nullish(), value: operationsValue2Request.nullish() })
  .transform((data) => ({
    op: data['op'],
    value: data['value'],
  }));
