// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const respondPanElementAddRequestStatus = z.enum(['denied', 'approved']);

export type RespondPanElementAddRequestStatus = z.infer<typeof respondPanElementAddRequestStatus>;
