// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum UpdatePanElementOrFolderElementType {
  API = 'api',
  FOLDER = 'folder',
  COLLECTION = 'collection',
  WORKSPACE = 'workspace',
}
