// This file was generated by liblab | https://liblab.com/

import { GetWorkspacesType } from './models/get-workspaces-type';
import { GetWorkspacesInclude } from './models/get-workspaces-include';

export interface GetWorkspacesParams {
  type?: GetWorkspacesType;
  createdBy?: number;
  include?: GetWorkspacesInclude;
}
