// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types';
import { RequestBuilder } from '../../http/transport/request-builder';
import { SerializationStyle } from '../../http/serialization/base-serializer';
import { GetWorkspaces, getWorkspacesResponse } from './models/get-workspaces';
import { GetWorkspacesParams } from './request-params';
import { CreateWorkspaceRequest, createWorkspaceRequestRequest } from './models/create-workspace-request';
import { CreateWorkspaceOkResponse, createWorkspaceOkResponseResponse } from './models/create-workspace-ok-response';
import { GetWorkspaceRoles, getWorkspaceRolesResponse } from './models/get-workspace-roles';
import { GetWorkspace, getWorkspaceResponse } from './models/get-workspace';
import { UpdateWorkspaceRequest, updateWorkspaceRequestRequest } from './models/update-workspace-request';
import { UpdateWorkspaceOkResponse, updateWorkspaceOkResponseResponse } from './models/update-workspace-ok-response';
import { DeleteWorkspace, deleteWorkspaceResponse } from './models/delete-workspace';
import {
  GetWorkspaceGlobalVariables,
  getWorkspaceGlobalVariablesResponse,
} from './models/get-workspace-global-variables';
import {
  UpdateWorkspaceGlobalVariablesRequest,
  updateWorkspaceGlobalVariablesRequestRequest,
} from './models/update-workspace-global-variables-request';
import {
  UpdateWorkspaceGlobalVariablesOkResponse,
  updateWorkspaceGlobalVariablesOkResponseResponse,
} from './models/update-workspace-global-variables-ok-response';
import {
  UpdateWorkspaceRolesRequest,
  updateWorkspaceRolesRequestRequest,
} from './models/update-workspace-roles-request';
import {
  UpdateWorkspaceRolesOkResponse,
  updateWorkspaceRolesOkResponseResponse,
} from './models/update-workspace-roles-ok-response';

export class WorkspacesService extends BaseService {
  /**
 * Gets all [workspaces](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/). The response includes your workspaces and any workspaces that you have access to.
**Note:**

This endpoint's response contains the visibility field. Visibility determines who can access the workspace:
- `personal` — Only you can access the workspace.
- `team` — All team members can access the workspace.
- `private` — Only invited team members can access the workspace ([**Professional** and **Enterprise** plans only](https://www.postman.com/pricing)).
- `public` — Everyone can access the workspace.
- `partner` — Only invited team members and [partners](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/partner-workspaces/) can access the workspace ([**Professional** and **Enterprise** plans only](https://www.postman.com/pricing)).

 * @param {GetWorkspacesType} [type] - The type of workspace to filter the response by.
 * @param {number} [createdBy] - Return only workspaces created by a specific user ID. For multiple users, pass this value as a comma-separated list of user IDs. The response only returns workspaces that you have access to.
 * @param {GetWorkspacesInclude} [include] - Include the following information in the endpoint's response:
- `mocks:deactivated` — Include all deactivated mock servers in the response.

 * @returns {Promise<HttpResponse<GetWorkspaces>>} Successful Response
 */
  async getWorkspaces(
    params?: GetWorkspacesParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetWorkspaces>> {
    const request = new RequestBuilder<GetWorkspaces>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/workspaces')
      .setRequestSchema(z.any())
      .setResponseSchema(getWorkspacesResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'type',
        value: params?.type,
      })
      .addQueryParam({
        key: 'createdBy',
        value: params?.createdBy,
      })
      .addQueryParam({
        key: 'include',
        value: params?.include,
      })
      .build();
    return this.client.call<GetWorkspaces>(request);
  }

  /**
 * Creates a new [workspace](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/creating-workspaces/).
**Note:**

This endpoint returns a 403 `Forbidden` response if the user does not have permission to create workspaces. [Admins and Super Admins](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles) can configure workspace permissions to restrict users and/or user groups from creating workspaces or require approvals for the creation of team workspaces.

### Important

We deprecated linking collections or environments between workspaces. We do not recommend that you do this.

If you have a linked collection or environment, note the following:
- The endpoint does not create a clone of a collection or environment.
- Any changes you make to a linked collection or environment changes them in all workspaces.
- If you delete a collection or environment linked between workspaces, the system deletes it in all the workspaces.

 * @returns {Promise<HttpResponse<CreateWorkspaceOkResponse>>} Successful Response
 */
  async createWorkspace(
    body: CreateWorkspaceRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CreateWorkspaceOkResponse>> {
    const request = new RequestBuilder<CreateWorkspaceOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('POST')
      .setPath('/workspaces')
      .setRequestSchema(createWorkspaceRequestRequest)
      .setResponseSchema(createWorkspaceOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CreateWorkspaceOkResponse>(request);
  }

  /**
   * Gets information about all roles in a workspace, based on the team's [plan](https://www.postman.com/pricing/).
   * @returns {Promise<HttpResponse<GetWorkspaceRoles>>} Successful Response
   */
  async getWorkspaceRoles(requestConfig?: RequestConfig): Promise<HttpResponse<GetWorkspaceRoles>> {
    const request = new RequestBuilder<GetWorkspaceRoles>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/workspaces-roles')
      .setRequestSchema(z.any())
      .setResponseSchema(getWorkspaceRolesResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .build();
    return this.client.call<GetWorkspaceRoles>(request);
  }

  /**
 * Gets information about a workspace.
**Note:**

This endpoint's response contains the `visibility` field. [Visibility](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#changing-workspace-visibility) determines who can access the workspace:
- `personal` — Only you can access the workspace.
- `team` — All team members can access the workspace.
- `private` — Only invited team members can access the workspace ([**Professional** and **Enterprise** plans only](https://www.postman.com/pricing)).
- `public` — Everyone can access the workspace.
- `partner` — Only invited team members and [partners](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/partner-workspaces/) can access the workspace ([**Professional** and **Enterprise** plans only](https://www.postman.com/pricing)).

### Important

We have deprecated the `name` and `uid` responses in the following array of objects:
- `collections`
- `environments`
- `mocks`
- `monitors`
- `apis`

 * @param {string} workspaceId - The workspace's ID.
 * @returns {Promise<HttpResponse<GetWorkspace>>} Successful Response
 */
  async getWorkspace(workspaceId: string, requestConfig?: RequestConfig): Promise<HttpResponse<GetWorkspace>> {
    const request = new RequestBuilder<GetWorkspace>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/workspaces/{workspaceId}')
      .setRequestSchema(z.any())
      .setResponseSchema(getWorkspaceResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'workspaceId',
        value: workspaceId,
      })
      .build();
    return this.client.call<GetWorkspace>(request);
  }

  /**
 * Updates a workspace.
### Important

We deprecated linking collections or environments between workspaces. We do not recommend that you do this.

If you have a linked collection or environment, note the following:
- The endpoint does not create a clone of a collection or environment.
- Any changes you make to a linked collection or environment changes them in all workspaces.
- If you delete a collection or environment linked between workspaces, the system deletes it in all the workspaces.

 * @param {string} workspaceId - The workspace's ID.
 * @returns {Promise<HttpResponse<UpdateWorkspaceOkResponse>>} Successful Response
 */
  async updateWorkspace(
    workspaceId: string,
    body: UpdateWorkspaceRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<UpdateWorkspaceOkResponse>> {
    const request = new RequestBuilder<UpdateWorkspaceOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/workspaces/{workspaceId}')
      .setRequestSchema(updateWorkspaceRequestRequest)
      .setResponseSchema(updateWorkspaceOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'workspaceId',
        value: workspaceId,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<UpdateWorkspaceOkResponse>(request);
  }

  /**
 * Deletes an existing workspace.
### Important

If you delete a workspace that has a linked collection or environment with another workspace, this will delete the collection and environment in all workspaces.

 * @param {string} workspaceId - The workspace's ID.
 * @returns {Promise<HttpResponse<DeleteWorkspace>>} Successful Response
 */
  async deleteWorkspace(workspaceId: string, requestConfig?: RequestConfig): Promise<HttpResponse<DeleteWorkspace>> {
    const request = new RequestBuilder<DeleteWorkspace>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('DELETE')
      .setPath('/workspaces/{workspaceId}')
      .setRequestSchema(z.any())
      .setResponseSchema(deleteWorkspaceResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'workspaceId',
        value: workspaceId,
      })
      .build();
    return this.client.call<DeleteWorkspace>(request);
  }

  /**
   * Gets a workspace's global [variables](https://learning.postman.com/docs/sending-requests/variables/#variable-scopes).
   * @param {string} workspaceId - The workspace's ID.
   * @returns {Promise<HttpResponse<GetWorkspaceGlobalVariables>>} Successful Response
   */
  async getWorkspaceGlobalVariables(
    workspaceId: string,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetWorkspaceGlobalVariables>> {
    const request = new RequestBuilder<GetWorkspaceGlobalVariables>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/workspaces/{workspaceId}/global-variables')
      .setRequestSchema(z.any())
      .setResponseSchema(getWorkspaceGlobalVariablesResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'workspaceId',
        value: workspaceId,
      })
      .build();
    return this.client.call<GetWorkspaceGlobalVariables>(request);
  }

  /**
   * Updates and replaces a workspace's global [variables](https://learning.postman.com/docs/sending-requests/variables/#variable-scopes). This endpoint replaces all existing global variables with the variables you pass in the request body.
   * @param {string} workspaceId - The workspace's ID.
   * @returns {Promise<HttpResponse<UpdateWorkspaceGlobalVariablesOkResponse>>} Successful Response
   */
  async updateWorkspaceGlobalVariables(
    workspaceId: string,
    body: UpdateWorkspaceGlobalVariablesRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<UpdateWorkspaceGlobalVariablesOkResponse>> {
    const request = new RequestBuilder<UpdateWorkspaceGlobalVariablesOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/workspaces/{workspaceId}/global-variables')
      .setRequestSchema(updateWorkspaceGlobalVariablesRequestRequest)
      .setResponseSchema(updateWorkspaceGlobalVariablesOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'workspaceId',
        value: workspaceId,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<UpdateWorkspaceGlobalVariablesOkResponse>(request);
  }

  /**
 * Updates the roles of [users](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles) or [user groups](https://learning.postman.com/docs/collaborating-in-postman/user-groups/) in a workspace. To get a list of roles, use the `GET /workspace-roles` endpoint.
**Note:**

- This endpoint does not support the external [Partner or Guest roles](https://learning.postman.com/docs/collaborating-in-postman/roles-and-permissions/#team-roles).
- This endpoint is restricted to 50 operations per call.
- The request body must contain one unique action per user or user group. For example, you cannot add and remove multiple roles for a user in the same request body.

 * @param {string} workspaceId - The workspace's ID.
 * @returns {Promise<HttpResponse<UpdateWorkspaceRolesOkResponse>>} Successful Response
 */
  async updateWorkspaceRoles(
    workspaceId: string,
    body: UpdateWorkspaceRolesRequest,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<UpdateWorkspaceRolesOkResponse>> {
    const request = new RequestBuilder<UpdateWorkspaceRolesOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PATCH')
      .setPath('/workspaces/{workspaceId}/roles')
      .setRequestSchema(updateWorkspaceRolesRequestRequest)
      .setResponseSchema(updateWorkspaceRolesOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'workspaceId',
        value: workspaceId,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json-patch+json' })
      .addBody(body)
      .build();
    return this.client.call<UpdateWorkspaceRolesOkResponse>(request);
  }
}
