// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createApiVersion2Schemas = z.lazy(() => {
  return z.object({
    filePath: z.string().optional(),
  });
});

/**
 * Information about the schema.
 * @typedef  {CreateApiVersion2Schemas} createApiVersion2Schemas - Information about the schema. - Information about the schema.
 * @property {string} - The path to the schema root file in the Git repository.
 */
export type CreateApiVersion2Schemas = z.infer<typeof createApiVersion2Schemas>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createApiVersion2SchemasResponse = z.lazy(() => {
  return z
    .object({
      filePath: z.string().optional(),
    })
    .transform((data) => ({
      filePath: data['filePath'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createApiVersion2SchemasRequest = z.lazy(() => {
  return z.object({ filePath: z.string().nullish() }).transform((data) => ({
    filePath: data['filePath'],
  }));
});
