// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createApiVersion1Collections = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
  });
});

/**
 * Information about the collection.
 * @typedef  {CreateApiVersion1Collections} createApiVersion1Collections - Information about the collection. - Information about the collection.
 * @property {string} - The collection's ID.
 */
export type CreateApiVersion1Collections = z.infer<typeof createApiVersion1Collections>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createApiVersion1CollectionsResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createApiVersion1CollectionsRequest = z.lazy(() => {
  return z.object({ id: z.string().nullish() }).transform((data) => ({
    id: data['id'],
  }));
});
