// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const createApiSchemaType2 = z.enum([
  'proto:2',
  'proto:3',
  'graphql',
  'openapi:3_1',
  'openapi:3',
  'openapi:2',
  'openapi:1',
  'raml:1',
  'raml:0_8',
  'wsdl:2',
  'wsdl:1',
  'asyncapi:2',
]);

export type CreateApiSchemaType2 = z.infer<typeof createApiSchemaType2>;
