// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getApiSchemaFilesMeta: any = z.lazy(() => {
  return z.object({
    nextCursor: z.string().optional(),
  });
});

/**
 * The schema's non-standard meta information.
 * @typedef  {GetApiSchemaFilesMeta} getApiSchemaFilesMeta - The schema's non-standard meta information. - The schema's non-standard meta information.
 * @property {string} - The pointer to the next record in the set of paginated results.
 */
export type GetApiSchemaFilesMeta = z.infer<typeof getApiSchemaFilesMeta>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getApiSchemaFilesMetaResponse: any = z.lazy(() => {
  return z
    .object({
      nextCursor: z.string().optional(),
    })
    .transform((data) => ({
      nextCursor: data['nextCursor'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getApiSchemaFilesMetaRequest: any = z.lazy(() => {
  return z.object({ nextCursor: z.string().nullish() }).transform((data) => ({
    nextCursor: data['nextCursor'],
  }));
});
