// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateApiOkResponse = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string(),
    summary: z.string().optional(),
    createdAt: z.string().optional(),
    createdBy: z.string().optional(),
    updatedAt: z.string().optional(),
    updatedBy: z.string().optional(),
    description: z.string().optional(),
  });
});

/**
 * Information about the API.
 * @typedef  {UpdateApiOkResponse} updateApiOkResponse - Information about the API. - Information about the API.
 * @property {string} - The API's ID.
 * @property {string} - The API's name.
 * @property {string} - The API's summary.
 * @property {string} - The date and time at which the API was created.
 * @property {string} - The user ID of the user that created the API.
 * @property {string} - The date and time at which the API was last updated.
 * @property {string} - The user ID of the user that updated the API.
 * @property {string} - The API's description. This supports Markdown formatting.
 */
export type UpdateApiOkResponse = z.infer<typeof updateApiOkResponse>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateApiOkResponseResponse = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string(),
      summary: z.string().optional(),
      createdAt: z.string().optional(),
      createdBy: z.string().optional(),
      updatedAt: z.string().optional(),
      updatedBy: z.string().optional(),
      description: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      summary: data['summary'],
      createdAt: data['createdAt'],
      createdBy: data['createdBy'],
      updatedAt: data['updatedAt'],
      updatedBy: data['updatedBy'],
      description: data['description'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateApiOkResponseRequest = z.lazy(() => {
  return z
    .object({
      id: z.string().nullish(),
      name: z.string().nullish(),
      summary: z.string().nullish(),
      createdAt: z.string().nullish(),
      createdBy: z.string().nullish(),
      updatedAt: z.string().nullish(),
      updatedBy: z.string().nullish(),
      description: z.string().nullish(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      summary: data['summary'],
      createdAt: data['createdAt'],
      createdBy: data['createdBy'],
      updatedAt: data['updatedAt'],
      updatedBy: data['updatedBy'],
      description: data['description'],
    }));
});
