// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getEnvironmentForksData: any = z.lazy(() => {
  return z.object({
    forkId: z.string().optional(),
    forkName: z.string().optional(),
    createdAt: z.string().optional(),
    createdBy: z.string().optional(),
    updatedAt: z.string().optional(),
  });
});

/**
 * Information about the forked environment.
 * @typedef  {GetEnvironmentForksData} getEnvironmentForksData - Information about the forked environment. - Information about the forked environment.
 * @property {string} - The forked environment's unique ID.
 * @property {string} - The forked environment's label.
 * @property {string} - The date and time at which the fork was created.
 * @property {string} - The user who created the environment fork.
 * @property {string} - The date and time at which the fork was last updated.
 */
export type GetEnvironmentForksData = z.infer<typeof getEnvironmentForksData>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getEnvironmentForksDataResponse: any = z.lazy(() => {
  return z
    .object({
      forkId: z.string().optional(),
      forkName: z.string().optional(),
      createdAt: z.string().optional(),
      createdBy: z.string().optional(),
      updatedAt: z.string().optional(),
    })
    .transform((data) => ({
      forkId: data['forkId'],
      forkName: data['forkName'],
      createdAt: data['createdAt'],
      createdBy: data['createdBy'],
      updatedAt: data['updatedAt'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getEnvironmentForksDataRequest: any = z.lazy(() => {
  return z
    .object({
      forkId: z.string().nullish(),
      forkName: z.string().nullish(),
      createdAt: z.string().nullish(),
      createdBy: z.string().nullish(),
      updatedAt: z.string().nullish(),
    })
    .transform((data) => ({
      forkId: data['forkId'],
      forkName: data['forkName'],
      createdAt: data['createdAt'],
      createdBy: data['createdBy'],
      updatedAt: data['updatedAt'],
    }));
});
