// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getEnvironmentForksSort = z.enum(['createdAt']);

export type GetEnvironmentForksSort = z.infer<typeof getEnvironmentForksSort>;
