// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const mergeEnvironmentForkRequest = z.object({
  source: z.string(),
  deleteSource: z.boolean().optional(),
});

/**
 *
 * @typedef  {MergeEnvironmentForkRequest} mergeEnvironmentForkRequest
 * @property {string} - The source environment's unique ID to merge data from.
 * @property {boolean} - If true, the forked environment will be deleted.
 */
export type MergeEnvironmentForkRequest = z.infer<typeof mergeEnvironmentForkRequest>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const mergeEnvironmentForkRequestResponse = z
  .object({
    source: z.string(),
    deleteSource: z.boolean().optional(),
  })
  .transform((data) => ({
    source: data['source'],
    deleteSource: data['deleteSource'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const mergeEnvironmentForkRequestRequest = z
  .object({ source: z.string().nullish(), deleteSource: z.boolean().nullish() })
  .transform((data) => ({
    source: data['source'],
    deleteSource: data['deleteSource'],
  }));
