// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const updateEnvironmentEnvironment2: any = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    uid: z.string().optional(),
  });
});

/**
 *
 * @typedef  {UpdateEnvironmentEnvironment2} updateEnvironmentEnvironment2
 * @property {string} - The environment's ID.
 * @property {string} - The environment's name.
 * @property {string} - The environment's unique ID.
 */
export type UpdateEnvironmentEnvironment2 = z.infer<typeof updateEnvironmentEnvironment2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const updateEnvironmentEnvironment2Response: any = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      uid: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      uid: data['uid'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const updateEnvironmentEnvironment2Request: any = z.lazy(() => {
  return z
    .object({ id: z.string().nullish(), name: z.string().nullish(), uid: z.string().nullish() })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      uid: data['uid'],
    }));
});
