// This file was generated by liblab | https://liblab.com/

import { Accept, AscDescDefaultDesc, accept, ascDescDefaultDesc } from '../common';
import { GetTaggedEntitiesEntityType, getTaggedEntitiesEntityType } from './models';

export interface GetApiTagsParams {
  accept: Accept;
}

export interface UpdateApiTagsParams {
  accept: Accept;
}

export interface GetTaggedEntitiesParams {
  limit?: number;
  direction?: AscDescDefaultDesc;
  cursor?: string;
  entityType?: GetTaggedEntitiesEntityType;
}
