// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { Request } from '../../http/transport/request';
import { TagGetPut, tagGetPutResponse } from './models/tag-get-put';
import { GetApiTagsParams, GetTaggedEntitiesParams, UpdateApiTagsParams } from './request-params';
import { TagUpdateTags, tagUpdateTagsRequest } from './models/tag-update-tags';
import { GetTaggedEntities, getTaggedEntitiesResponse } from './models/get-tagged-entities';

export class TagsService extends BaseService {
  /**
   * Gets all the tags associated with an API.
   * @param {string} apiId - The API's unique ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<TagGetPut>>} Success Response
   */
  async getApiTags(
    apiId: string,
    params: GetApiTagsParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<TagGetPut>> {
    const request = new Request({
      method: 'GET',
      path: '/apis/{apiId}/tags',
      config: this.config,
      responseSchema: tagGetPutResponse,
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('apiId', apiId);
    request.addHeaderParam('Accept', params?.accept);
    return this.client.call<TagGetPut>(request);
  }

  /**
   * Updates an API's associated tags. This endpoint replaces all existing tags with those you pass in the request body.
   * @param {string} apiId - The API's unique ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<TagGetPut>>} Success Response
   */
  async updateApiTags(
    apiId: string,
    body: TagUpdateTags,
    params: UpdateApiTagsParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<TagGetPut>> {
    const request = new Request({
      method: 'PUT',
      body,
      path: '/apis/{apiId}/tags',
      config: this.config,
      responseSchema: tagGetPutResponse,
      requestSchema: tagUpdateTagsRequest,
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('apiId', apiId);
    request.addHeaderParam('Accept', params?.accept);
    request.addHeaderParam('Content-Type', 'application/json');
    return this.client.call<TagGetPut>(request);
  }

  /**
   * Gets all the tags associated with a collection.
   * @param {string} collectionId - The collection's unique ID.
   * @returns {Promise<HttpResponse<TagGetPut>>} Success Response
   */
  async getCollectionTags(collectionId: string, requestConfig?: RequestConfig): Promise<HttpResponse<TagGetPut>> {
    const request = new Request({
      method: 'GET',
      path: '/collections/{collectionId}/tags',
      config: this.config,
      responseSchema: tagGetPutResponse,
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('collectionId', collectionId);
    return this.client.call<TagGetPut>(request);
  }

  /**
   * Updates a collection's associated tags. This endpoint replaces all existing tags with those you pass in the request body.
   * @param {string} collectionId - The collection's unique ID.
   * @returns {Promise<HttpResponse<TagGetPut>>} Success Response
   */
  async updateCollectionTags(
    collectionId: string,
    body: TagUpdateTags,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<TagGetPut>> {
    const request = new Request({
      method: 'PUT',
      body,
      path: '/collections/{collectionId}/tags',
      config: this.config,
      responseSchema: tagGetPutResponse,
      requestSchema: tagUpdateTagsRequest,
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('collectionId', collectionId);
    request.addHeaderParam('Content-Type', 'application/json');
    return this.client.call<TagGetPut>(request);
  }

  /**
 * Gets Postman elements (entities) by a given tag. Tags enable you to organize and search [workspaces](https://learning.postman.com/docs/collaborating-in-postman/using-workspaces/managing-workspaces/#tagging-a-workspace), [APIs](https://learning.postman.com/docs/designing-and-developing-your-api/managing-apis/#tagging-apis), and [collections](https://learning.postman.com/docs/collections/using-collections/#tagging-a-collection) that contain shared tags.
**Note:**

Tagging is available on Postman [**Enterprise** plans](https://www.postman.com/pricing/).

 * @param {string} slug - The tag's ID within a team or individual (non-team) user scope.
 * @param {number} [limit] - The maximum number of tagged elements to return in a single call.
 * @param {AscDescDefaultDesc} [direction] - The ascending (`asc`) or descending (`desc`) order to sort the results by, based on the time of the entity's tagging.
 * @param {string} [cursor] - The cursor to get the next set of results in the paginated response. If you pass an invalid value, the API only returns the first set of results.
 * @param {GetTaggedEntitiesEntityType} [entityType] - Filter results for the given entity type.
 * @returns {Promise<HttpResponse<GetTaggedEntities>>} Successful Response
 */
  async getTaggedEntities(
    slug: string,
    params?: GetTaggedEntitiesParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetTaggedEntities>> {
    const request = new Request({
      method: 'GET',
      path: '/tags/{slug}/entities',
      config: this.config,
      responseSchema: getTaggedEntitiesResponse,
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('slug', slug);
    request.addQueryParam('limit', params?.limit);
    request.addQueryParam('direction', params?.direction);
    request.addQueryParam('cursor', params?.cursor);
    request.addQueryParam('entityType', params?.entityType);
    return this.client.call<GetTaggedEntities>(request);
  }

  /**
   * Gets all the tags associated with a workspace.
   * @param {string} workspaceId - The workspace's ID.
   * @returns {Promise<HttpResponse<TagGetPut>>} Success Response
   */
  async getWorkspaceTags(workspaceId: string, requestConfig?: RequestConfig): Promise<HttpResponse<TagGetPut>> {
    const request = new Request({
      method: 'GET',
      path: '/workspaces/{workspaceId}/tags',
      config: this.config,
      responseSchema: tagGetPutResponse,
      requestSchema: z.any(),
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('workspaceId', workspaceId);
    return this.client.call<TagGetPut>(request);
  }

  /**
   * Updates a workspace's associated tags. This endpoint replaces all existing tags with those you pass in the request body.
   * @param {string} workspaceId - The workspace's ID.
   * @returns {Promise<HttpResponse<TagGetPut>>} Success Response
   */
  async updateWorkspaceTags(
    workspaceId: string,
    body: TagUpdateTags,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<TagGetPut>> {
    const request = new Request({
      method: 'PUT',
      body,
      path: '/workspaces/{workspaceId}/tags',
      config: this.config,
      responseSchema: tagGetPutResponse,
      requestSchema: tagUpdateTagsRequest,
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      requestConfig,
    });
    request.addPathParam('workspaceId', workspaceId);
    request.addHeaderParam('Content-Type', 'application/json');
    return this.client.call<TagGetPut>(request);
  }
}
