// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getMonitorsMonitors: any = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    owner: z.string().optional(),
    uid: z.string().optional(),
  });
});

/**
 *
 * @typedef  {GetMonitorsMonitors} getMonitorsMonitors
 * @property {string} - The monitor's ID.
 * @property {string} - The monitor's name.
 * @property {string} - The ID of the monitor's owner.
 * @property {string} - The monitor's unique ID.
 */
export type GetMonitorsMonitors = z.infer<typeof getMonitorsMonitors>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getMonitorsMonitorsResponse: any = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      owner: z.string().optional(),
      uid: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      owner: data['owner'],
      uid: data['uid'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getMonitorsMonitorsRequest: any = z.lazy(() => {
  return z
    .object({
      id: z.string().nullish(),
      name: z.string().nullish(),
      owner: z.string().nullish(),
      uid: z.string().nullish(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      owner: data['owner'],
      uid: data['uid'],
    }));
});
