// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse, RequestConfig } from '../../http/types';
import { RequestBuilder } from '../../http/transport/request-builder';
import { SerializationStyle } from '../../http/serialization/base-serializer';
import { GetApis, getApisResponse } from './models/get-apis';
import {
  AddApiCollectionParams,
  CreateApiParams,
  CreateApiSchemaParams,
  CreateApiVersionParams,
  CreateUpdateApiSchemaFileParams,
  DeleteApiParams,
  DeleteApiSchemaFileParams,
  DeleteApiVersionParams,
  GetApiCollectionParams,
  GetApiParams,
  GetApiSchemaFileContentsParams,
  GetApiSchemaFilesParams,
  GetApiSchemaParams,
  GetApiVersionParams,
  GetApiVersionsParams,
  GetApisParams,
  GetStatusOfAnAsyncTaskParams,
  SyncCollectionWithSchemaParams,
  UpdateApiParams,
  UpdateApiVersionParams,
} from './request-params';
import { CreateApiRequest, createApiRequestRequest } from './models/create-api-request';
import { CreateApiOkResponse, createApiOkResponseResponse } from './models/create-api-ok-response';
import { GetApi, getApiResponse } from './models/get-api';
import { UpdateApiRequest, updateApiRequestRequest } from './models/update-api-request';
import { UpdateApiOkResponse, updateApiOkResponseResponse } from './models/update-api-ok-response';
import { AddApiCollectionRequest, addApiCollectionRequestRequest } from './models/add-api-collection-request';
import {
  AddApiCollectionOkResponse,
  addApiCollectionOkResponseResponse,
} from './models/add-api-collection-ok-response';
import { SyncCollectionWithSchema, syncCollectionWithSchemaResponse } from './models/sync-collection-with-schema';
import { CommentResponse, commentResponseResponse } from '../common/comment-response';
import { CommentCreateUpdate, commentCreateUpdateRequest } from '../common/comment-create-update';
import { CommentCreatedUpdated, commentCreatedUpdatedResponse } from '../common/comment-created-updated';
import { CreateApiSchemaRequest, createApiSchemaRequestRequest } from './models/create-api-schema-request';
import { CreateApiSchemaOkResponse, createApiSchemaOkResponseResponse } from './models/create-api-schema-ok-response';
import { GetApiSchema, getApiSchemaResponse } from './models/get-api-schema';
import { GetApiSchemaFiles, getApiSchemaFilesResponse } from './models/get-api-schema-files';
import { GetApiSchemaFileContents, getApiSchemaFileContentsResponse } from './models/get-api-schema-file-contents';
import {
  CreateUpdateApiSchemaFileRequest,
  createUpdateApiSchemaFileRequestRequest,
} from './models/create-update-api-schema-file-request';
import {
  CreateUpdateApiSchemaFileOkResponse,
  createUpdateApiSchemaFileOkResponseResponse,
} from './models/create-update-api-schema-file-ok-response';
import { GetStatusOfAnAsyncTask, getStatusOfAnAsyncTaskResponse } from './models/get-status-of-an-async-task';
import { GetApiVersions, getApiVersionsResponse } from './models/get-api-versions';
import { CreateApiVersionRequest, createApiVersionRequestRequest } from './models/create-api-version-request';
import {
  CreateApiVersionAcceptedResponse,
  createApiVersionAcceptedResponseResponse,
} from './models/create-api-version-accepted-response';
import { GetApiVersion, getApiVersionResponse } from './models/get-api-version';
import { UpdateApiVersionRequest, updateApiVersionRequestRequest } from './models/update-api-version-request';
import {
  UpdateApiVersionOkResponse,
  updateApiVersionOkResponseResponse,
} from './models/update-api-version-ok-response';

export class ApiService extends BaseService {
  /**
   * Gets information about all APIs in a workspace.
   * @param {string} workspaceId - The workspace's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @param {number} [createdBy] - Return only results created by the given user ID.
   * @param {string} [cursor] - The pointer to the first record of the set of paginated results. To view the next response, use the `nextCursor` value for this parameter.
   * @param {string} [description] - Return only APIs whose description includes the given value. Matching is not case-sensitive.
   * @param {number} [limit] - The maximum number of rows to return in the response.
   * @returns {Promise<HttpResponse<GetApis>>} Successful Response
   */
  async getApis(params: GetApisParams, requestConfig?: RequestConfig): Promise<HttpResponse<GetApis>> {
    const request = new RequestBuilder<GetApis>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis')
      .setRequestSchema(z.any())
      .setResponseSchema(getApisResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'workspaceId',
        value: params?.workspaceId,
      })
      .addQueryParam({
        key: 'createdBy',
        value: params?.createdBy,
      })
      .addQueryParam({
        key: 'cursor',
        value: params?.cursor,
      })
      .addQueryParam({
        key: 'description',
        value: params?.description,
      })
      .addQueryParam({
        key: 'limit',
        value: params?.limit,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApis>(request);
  }

  /**
   * Creates an API.
   * @param {string} workspaceId - The workspace's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<CreateApiOkResponse>>} Successful Response
   */
  async createApi(
    body: CreateApiRequest,
    params: CreateApiParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CreateApiOkResponse>> {
    const request = new RequestBuilder<CreateApiOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('POST')
      .setPath('/apis')
      .setRequestSchema(createApiRequestRequest)
      .setResponseSchema(createApiOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addQueryParam({
        key: 'workspaceId',
        value: params?.workspaceId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CreateApiOkResponse>(request);
  }

  /**
 * Gets information about an API.
**Note:**

- Git-connected APIs will only return the `versions` and `gitInfo` query responses. This is because schema and collection information is stored in the connected Git repository. The `gitInfo` object only lists the repository and folder locations of the files.
- API viewers can only use the `versions` option in the `include` query parameter.

 * @param {string} apiId - The API's ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @param {GetApiInclude[]} [include] - An array that contains additional resources to include in the response. Use this parameter to query for element links to the API, such as  collections and schemas:
- `collections` — Query for linked Postman collections.
- `versions` — Query for linked versions.
- `schemas` — Query for linked schemas.
- `gitInfo` — Query for information about the API's git-linked repository. This query only returns the linked repository and folder locations of the files. It does not return `collections` or `schemas` information.

**Note:**

API viewers can only use the `versions` option.

 * @returns {Promise<HttpResponse<GetApi>>} Successful Response
 */
  async getApi(apiId: string, params: GetApiParams, requestConfig?: RequestConfig): Promise<HttpResponse<GetApi>> {
    const request = new RequestBuilder<GetApi>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}')
      .setRequestSchema(z.any())
      .setResponseSchema(getApiResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addQueryParam({
        key: 'include',
        value: params?.include,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApi>(request);
  }

  /**
   * Updates an API.
   * @param {string} apiId - The API's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<UpdateApiOkResponse>>} Successful Response
   */
  async updateApi(
    apiId: string,
    body: UpdateApiRequest,
    params: UpdateApiParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<UpdateApiOkResponse>> {
    const request = new RequestBuilder<UpdateApiOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/apis/{apiId}')
      .setRequestSchema(updateApiRequestRequest)
      .setResponseSchema(updateApiOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<UpdateApiOkResponse>(request);
  }

  /**
   * Deletes an API.
   * @param {string} apiId - The API's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<any>>} No Content
   */
  async deleteApi(
    apiId: string,
    params: DeleteApiParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<undefined>> {
    const request = new RequestBuilder<undefined>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('DELETE')
      .setPath('/apis/{apiId}')
      .setRequestSchema(z.any())
      .setResponseSchema(z.undefined())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<undefined>(request);
  }

  /**
 * Adds a collection to an API. To do this, use the following `operationType` values:
- `COPY_COLLECTION` — Copies a collection from the workspace and adds it to an API.
- `CREATE_NEW` — Creates a new collection by providing the new collection's content.
- `GENERATE_FROM_SCHEMA` — Generates the collection from an API schema.
    - `options` — An object that contains advanced creation options and their values. You can find a complete list of properties and their values in Postman's [OpenAPI 3.0 to Postman Collection v2.1.0 Converter OPTIONS documentation](https://github.com/postmanlabs/openapi-to-postman/blob/develop/OPTIONS.md). These properties are case-sensitive.

 * @param {string} apiId - The API's ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<AddApiCollectionOkResponse>>} Created
 */
  async addApiCollection(
    apiId: string,
    body: AddApiCollectionRequest,
    params: AddApiCollectionParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<AddApiCollectionOkResponse>> {
    const request = new RequestBuilder<AddApiCollectionOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('POST')
      .setPath('/apis/{apiId}/collections')
      .setRequestSchema(addApiCollectionRequestRequest)
      .setResponseSchema(addApiCollectionOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<AddApiCollectionOkResponse>(request);
  }

  /**
 * Gets a collection attached to an API. You can use the `versionId` query parameter to get a collection published in a version.
**Note:**

The `versionId` query parameter is a required parameter for API viewers.

 * @param {string} apiId - The API's ID.
 * @param {string} collectionId - The collection's unique ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @param {string} [versionId] - The API's version ID.
 * @returns {Promise<HttpResponse<any>>} Successful Response
 */
  async getApiCollection(
    apiId: string,
    collectionId: string,
    params: GetApiCollectionParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<any>> {
    const request = new RequestBuilder<any>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/collections/{collectionId}')
      .setRequestSchema(z.any())
      .setResponseSchema(z.any())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'collectionId',
        value: collectionId,
      })
      .addQueryParam({
        key: 'versionId',
        value: params?.versionId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<any>(request);
  }

  /**
 * Syncs a collection attached to an API with the API schema.
This is an asynchronous endpoint that returns an HTTP `202 Accepted` response. The response contains a polling link to the `/apis/{apiId}/tasks/{taskId}` endpoint in the `Location` header.

**Note:**

This endpoint only supports the OpenAPI 3 schema type.

 * @param {string} apiId - The API's ID.
 * @param {string} collectionId - The collection's unique ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<SyncCollectionWithSchema>>} Accepted
 */
  async syncCollectionWithSchema(
    apiId: string,
    collectionId: string,
    params: SyncCollectionWithSchemaParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<SyncCollectionWithSchema>> {
    const request = new RequestBuilder<SyncCollectionWithSchema>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/apis/{apiId}/collections/{collectionId}/sync-with-schema-tasks')
      .setRequestSchema(z.any())
      .setResponseSchema(syncCollectionWithSchemaResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'collectionId',
        value: collectionId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<SyncCollectionWithSchema>(request);
  }

  /**
   * Gets all comments left by users in an API.
   * @param {string} apiId - The API's ID.
   * @returns {Promise<HttpResponse<CommentResponse>>} Successful Response
   */
  async getApiComments(apiId: string, requestConfig?: RequestConfig): Promise<HttpResponse<CommentResponse>> {
    const request = new RequestBuilder<CommentResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/comments')
      .setRequestSchema(z.any())
      .setResponseSchema(commentResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .build();
    return this.client.call<CommentResponse>(request);
  }

  /**
 * Creates a comment on an API.
**Note:**

This endpoint accepts a max of 10,000 characters.

 * @param {string} apiId - The API's ID.
 * @returns {Promise<HttpResponse<CommentCreatedUpdated>>} Created
 */
  async createApiComment(
    apiId: string,
    body: CommentCreateUpdate,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CommentCreatedUpdated>> {
    const request = new RequestBuilder<CommentCreatedUpdated>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('POST')
      .setPath('/apis/{apiId}/comments')
      .setRequestSchema(commentCreateUpdateRequest)
      .setResponseSchema(commentCreatedUpdatedResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CommentCreatedUpdated>(request);
  }

  /**
 * Updates a comment on an API.
**Note:**

This endpoint accepts a max of 10,000 characters.

 * @param {string} apiId - The API's ID.
 * @param {number} commentId - The comment's ID.
 * @returns {Promise<HttpResponse<CommentCreatedUpdated>>} Successful Response
 */
  async updateApiComment(
    apiId: string,
    commentId: number,
    body: CommentCreateUpdate,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CommentCreatedUpdated>> {
    const request = new RequestBuilder<CommentCreatedUpdated>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/apis/{apiId}/comments/{commentId}')
      .setRequestSchema(commentCreateUpdateRequest)
      .setResponseSchema(commentCreatedUpdatedResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'commentId',
        value: commentId,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CommentCreatedUpdated>(request);
  }

  /**
 * Deletes a comment from an API. On success, this returns an HTTP `204 No Content` response.
**Note:**

Deleting the first comment of a thread deletes all the comments in the thread.

 * @param {string} apiId - The API's ID.
 * @param {number} commentId - The comment's ID.
 * @returns {Promise<HttpResponse<any>>} No Content
 */
  async deleteApiComment(
    apiId: string,
    commentId: number,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<undefined>> {
    const request = new RequestBuilder<undefined>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('DELETE')
      .setPath('/apis/{apiId}/comments/{commentId}')
      .setRequestSchema(z.any())
      .setResponseSchema(z.undefined())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'commentId',
        value: commentId,
      })
      .build();
    return this.client.call<undefined>(request);
  }

  /**
   * Creates a schema for an API.
   * @param {string} apiId - The API's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<CreateApiSchemaOkResponse>>} Created
   */
  async createApiSchema(
    apiId: string,
    body: CreateApiSchemaRequest,
    params: CreateApiSchemaParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CreateApiSchemaOkResponse>> {
    const request = new RequestBuilder<CreateApiSchemaOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('POST')
      .setPath('/apis/{apiId}/schemas')
      .setRequestSchema(createApiSchemaRequestRequest)
      .setResponseSchema(createApiSchemaOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CreateApiSchemaOkResponse>(request);
  }

  /**
 * Gets information about API schema. You can use the `versionId` query parameter to get a schema published in an API version.
You can use this API to do the following:

- Get a schema's metadata.
- Get all the files in a schema. This only returns the first file in the schema. The endpoint response contains a link to the next set of response results.
- Get a schema's contents in multi-file or bundled format.

**Note:**

The `versionId` query parameter is a required parameter for API viewers.

 * @param {string} apiId - The API's ID.
 * @param {string} schemaId - The API schema's ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @param {string} [versionId] - The API's version ID.
 * @param {boolean} [bundled] - If true, return the schema in a bundled format.
 * @returns {Promise<HttpResponse<GetApiSchema>>} Successful Response
 */
  async getApiSchema(
    apiId: string,
    schemaId: string,
    params: GetApiSchemaParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetApiSchema>> {
    const request = new RequestBuilder<GetApiSchema>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/schemas/{schemaId}')
      .setRequestSchema(z.any())
      .setResponseSchema(getApiSchemaResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'schemaId',
        value: schemaId,
      })
      .addQueryParam({
        key: 'versionId',
        value: params?.versionId,
      })
      .addQueryParam({
        key: 'bundled',
        value: params?.bundled,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApiSchema>(request);
  }

  /**
 * Gets the files in an API schema. You can use the `versionId` query parameter to get schema files published in an API version.
**Note:**

The `versionId` query parameter is a required parameter for API viewers.

 * @param {string} apiId - The API's ID.
 * @param {string} schemaId - The API schema's ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @param {string} [versionId] - The API's version ID.
 * @param {number} [limit] - The maximum number of rows to return in the response.
 * @param {string} [cursor] - The pointer to the first record of the set of paginated results. To view the next response, use the `nextCursor` value for this parameter.
 * @returns {Promise<HttpResponse<GetApiSchemaFiles>>} Successful Response
 */
  async getApiSchemaFiles(
    apiId: string,
    schemaId: string,
    params: GetApiSchemaFilesParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetApiSchemaFiles>> {
    const request = new RequestBuilder<GetApiSchemaFiles>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/schemas/{schemaId}/files')
      .setRequestSchema(z.any())
      .setResponseSchema(getApiSchemaFilesResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'schemaId',
        value: schemaId,
      })
      .addQueryParam({
        key: 'versionId',
        value: params?.versionId,
      })
      .addQueryParam({
        key: 'limit',
        value: params?.limit,
      })
      .addQueryParam({
        key: 'cursor',
        value: params?.cursor,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApiSchemaFiles>(request);
  }

  /**
 * Gets an API schema file contents at the defined path. You can use the `versionId` query parameter to get schema file contents published in an API version.
**Note:**

The `versionId` query parameter is a required parameter for API viewers.

 * @param {string} apiId - The API's ID.
 * @param {string} schemaId - The API schema's ID.
 * @param {string} filePath - The path to the schema file.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @param {string} [versionId] - The API's version ID.
 * @returns {Promise<HttpResponse<GetApiSchemaFileContents>>} Successful Response
 */
  async getApiSchemaFileContents(
    apiId: string,
    schemaId: string,
    filePath: string,
    params: GetApiSchemaFileContentsParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetApiSchemaFileContents>> {
    const request = new RequestBuilder<GetApiSchemaFileContents>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/schemas/{schemaId}/files/{file-path}')
      .setRequestSchema(z.any())
      .setResponseSchema(getApiSchemaFileContentsResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'schemaId',
        value: schemaId,
      })
      .addPathParam({
        key: 'file-path',
        value: filePath,
      })
      .addQueryParam({
        key: 'versionId',
        value: params?.versionId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApiSchemaFileContents>(request);
  }

  /**
 * Creates or updates an API schema file.
**Note:**

- If the provided file path exists, the file will be updated with the new contents.
- If the provided file path does not exist, then a new schema file will be created.
- If the file path contains a `/` (forward slash) character, then a folder is created. For example, if the file path is the `dir/schema.json` value, then a `dir` folder is created with the `schema.json` file inside.

 * @param {string} apiId - The API's ID.
 * @param {string} schemaId - The API schema's ID.
 * @param {string} filePath - The path to the schema file.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<CreateUpdateApiSchemaFileOkResponse>>} Successful Response
 */
  async createUpdateApiSchemaFile(
    apiId: string,
    schemaId: string,
    filePath: string,
    body: CreateUpdateApiSchemaFileRequest,
    params: CreateUpdateApiSchemaFileParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CreateUpdateApiSchemaFileOkResponse>> {
    const request = new RequestBuilder<CreateUpdateApiSchemaFileOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/apis/{apiId}/schemas/{schemaId}/files/{file-path}')
      .setRequestSchema(createUpdateApiSchemaFileRequestRequest)
      .setResponseSchema(createUpdateApiSchemaFileOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'schemaId',
        value: schemaId,
      })
      .addPathParam({
        key: 'file-path',
        value: filePath,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CreateUpdateApiSchemaFileOkResponse>(request);
  }

  /**
   * Deletes a file in an API schema.
   * @param {string} apiId - The API's ID.
   * @param {string} schemaId - The API schema's ID.
   * @param {string} filePath - The path to the schema file.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<any>>} Deleted
   */
  async deleteApiSchemaFile(
    apiId: string,
    schemaId: string,
    filePath: string,
    params: DeleteApiSchemaFileParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<undefined>> {
    const request = new RequestBuilder<undefined>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('DELETE')
      .setPath('/apis/{apiId}/schemas/{schemaId}/files/{file-path}')
      .setRequestSchema(z.any())
      .setResponseSchema(z.undefined())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'schemaId',
        value: schemaId,
      })
      .addPathParam({
        key: 'file-path',
        value: filePath,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<undefined>(request);
  }

  /**
   * Gets the status of an asynchronous task.
   * @param {string} apiId - The API's ID.
   * @param {string} taskId - The task's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @returns {Promise<HttpResponse<GetStatusOfAnAsyncTask>>} Successful Response
   */
  async getStatusOfAnAsyncTask(
    apiId: string,
    taskId: string,
    params: GetStatusOfAnAsyncTaskParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetStatusOfAnAsyncTask>> {
    const request = new RequestBuilder<GetStatusOfAnAsyncTask>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/tasks/{taskId}')
      .setRequestSchema(z.any())
      .setResponseSchema(getStatusOfAnAsyncTaskResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'taskId',
        value: taskId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetStatusOfAnAsyncTask>(request);
  }

  /**
   * Gets all the published versions of an API.
   * @param {string} apiId - The API's ID.
   * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
   * @param {string} [cursor] - The pointer to the first record of the set of paginated results. To view the next response, use the `nextCursor` value for this parameter.
   * @param {number} [limit] - The maximum number of rows to return in the response.
   * @returns {Promise<HttpResponse<GetApiVersions>>} Successful Response
   */
  async getApiVersions(
    apiId: string,
    params: GetApiVersionsParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetApiVersions>> {
    const request = new RequestBuilder<GetApiVersions>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/versions')
      .setRequestSchema(z.any())
      .setResponseSchema(getApiVersionsResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addQueryParam({
        key: 'cursor',
        value: params?.cursor,
      })
      .addQueryParam({
        key: 'limit',
        value: params?.limit,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApiVersions>(request);
  }

  /**
 * Creates a new API version asynchronously and immediately returns an HTTP `202 Accepted` response. The response contains a polling link to the task status API in the `Location` header.
This endpoint is equivalent to publishing a version in Postman app, which is the snapshot of API collections and schema at a given point in time.

 * @param {string} apiId - The API's ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<CreateApiVersionAcceptedResponse>>} Accepted
 */
  async createApiVersion(
    apiId: string,
    body: CreateApiVersionRequest,
    params: CreateApiVersionParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<CreateApiVersionAcceptedResponse>> {
    const request = new RequestBuilder<CreateApiVersionAcceptedResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('POST')
      .setPath('/apis/{apiId}/versions')
      .setRequestSchema(createApiVersionRequestRequest)
      .setResponseSchema(createApiVersionAcceptedResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<CreateApiVersionAcceptedResponse>(request);
  }

  /**
 * Gets information about an API version.
**Note:**

- For API editors, this endpoint returns an HTTP `302 Found` status code when the version status is pending. It also returns the `/apis/{apiId}/tasks/{taskId}` task status response header.
- For API viewers, this endpoint returns an HTTP `404 Not Found` when the version status is pending.

 * @param {string} apiId - The API's ID.
 * @param {string} versionId - The API's version ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<GetApiVersion>>} Successful Response
 */
  async getApiVersion(
    apiId: string,
    versionId: string,
    params: GetApiVersionParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<GetApiVersion>> {
    const request = new RequestBuilder<GetApiVersion>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('GET')
      .setPath('/apis/{apiId}/versions/{versionId}')
      .setRequestSchema(z.any())
      .setResponseSchema(getApiVersionResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'versionId',
        value: versionId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<GetApiVersion>(request);
  }

  /**
 * Updates an API version.
**Note:**

This endpoint returns an HTTP `404 Not Found` response when an API version is pending publication.

 * @param {string} apiId - The API's ID.
 * @param {string} versionId - The API's version ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<UpdateApiVersionOkResponse>>} Successful Response
 */
  async updateApiVersion(
    apiId: string,
    versionId: string,
    body: UpdateApiVersionRequest,
    params: UpdateApiVersionParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<UpdateApiVersionOkResponse>> {
    const request = new RequestBuilder<UpdateApiVersionOkResponse>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('PUT')
      .setPath('/apis/{apiId}/versions/{versionId}')
      .setRequestSchema(updateApiVersionRequestRequest)
      .setResponseSchema(updateApiVersionOkResponseResponse)
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'versionId',
        value: versionId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .addHeaderParam({ key: 'Content-Type', value: 'application/json' })
      .addBody(body)
      .build();
    return this.client.call<UpdateApiVersionOkResponse>(request);
  }

  /**
 * Deletes an API version.
**Note:**

This endpoint returns an HTTP `404 Not Found` response when an API version is pending publication.

 * @param {string} apiId - The API's ID.
 * @param {string} versionId - The API's version ID.
 * @param {Accept} accept - The `application/vnd.api.v10+json` request header required to use the endpoint.
 * @returns {Promise<HttpResponse<any>>} No Content
 */
  async deleteApiVersion(
    apiId: string,
    versionId: string,
    params: DeleteApiVersionParams,
    requestConfig?: RequestConfig,
  ): Promise<HttpResponse<undefined>> {
    const request = new RequestBuilder<undefined>()
      .setConfig(this.config)
      .setBaseUrl(this.config)
      .setMethod('DELETE')
      .setPath('/apis/{apiId}/versions/{versionId}')
      .setRequestSchema(z.any())
      .setResponseSchema(z.undefined())
      .setRequestContentType(ContentType.Json)
      .setResponseContentType(ContentType.Json)
      .setRetryAttempts(this.config, requestConfig)
      .setRetryDelayMs(this.config, requestConfig)
      .setResponseValidation(this.config, requestConfig)
      .addPathParam({
        key: 'apiId',
        value: apiId,
      })
      .addPathParam({
        key: 'versionId',
        value: versionId,
      })
      .addHeaderParam({
        key: 'Accept',
        value: params?.accept,
      })
      .build();
    return this.client.call<undefined>(request);
  }
}
