// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { BaseService } from '../base-service';
import { ContentType, HttpResponse } from '../../http';
import { RequestConfig } from '../../http/types';
import { GetAuditLogs, getAuditLogsResponse } from './models';
import { GetAuditLogsParams } from './request-params';

export class AuditLogsService extends BaseService {
  /**
   * Gets a list of your team's generated audit events. For a complete list of all audit events, read our [Utilizing audit logs](https://learning.postman.com/docs/administration/audit-logs/) documentation.
   * @param {string} [since] - Return logs created after the given time, in `YYYY-MM-DD` format.
   * @param {string} [until] - Return logs created before the given time, in `YYYY-MM-DD` format.
   * @param {number} [limit] - The maximum number of audit events to return at once.
   * @param {string} [cursor] - The pointer to the first record of the set of paginated results. To view the next response, use the `nextCursor` value for this parameter.
   * @param {AscDescDefaultDesc} [orderBy] - Return the records in ascending (`asc`) or descending (`desc`) order.
   * @returns {Promise<HttpResponse<GetAuditLogs>>} Successful Response
   */
  async getAuditLogs(params?: GetAuditLogsParams, requestConfig?: RequestConfig): Promise<HttpResponse<GetAuditLogs>> {
    const path = '/audit/logs';
    const options: any = {
      responseSchema: getAuditLogsResponse,
      requestSchema: z.any(),
      queryParams: {},
      headers: {},
      requestContentType: ContentType.Json,
      responseContentType: ContentType.Json,
      retry: requestConfig?.retry,
      config: this.config,
    };
    if (params?.since) {
      options.queryParams['since'] = params?.since;
    }
    if (params?.until) {
      options.queryParams['until'] = params?.until;
    }
    if (params?.limit) {
      options.queryParams['limit'] = params?.limit;
    }
    if (params?.cursor) {
      options.queryParams['cursor'] = params?.cursor;
    }
    if (params?.orderBy) {
      options.queryParams['order_by'] = params?.orderBy;
    }
    return this.client.get(path, options);
  }
}
