// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const jsonStringifiedType = z.enum(['json']);

export type JsonStringifiedType = z.infer<typeof jsonStringifiedType>;
