// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const mergeStatus = z.enum(['inactive', 'inprogress', 'failed']);

export type MergeStatus = z.infer<typeof mergeStatus>;
