// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const strategy = z.enum(['deleteSource', 'updateSourceWithDestination']);

export type Strategy = z.infer<typeof strategy>;
