// This file was generated by liblab | https://liblab.com/

export interface CreateCollectionRequestParams {
  folderId?: string;
}

export interface CreateCollectionResponseParams {
  requestId: string;
}

export interface GetCollectionFolderParams {
  ids?: boolean;
  uid?: boolean;
  populate?: boolean;
}

export interface GetCollectionRequestParams {
  ids?: boolean;
  uid?: boolean;
  populate?: boolean;
}

export interface GetCollectionResponseParams {
  ids?: boolean;
  uid?: boolean;
  populate?: boolean;
}
