// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const createWorkspaceWorkspace2 = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string().optional(),
  });
});

/**
 * Information about the created workspace.
 * @typedef  {CreateWorkspaceWorkspace2} createWorkspaceWorkspace2 - Information about the created workspace. - Information about the created workspace.
 * @property {string} - The workspace's ID.
 * @property {string} - The workspace's name.
 */
export type CreateWorkspaceWorkspace2 = z.infer<typeof createWorkspaceWorkspace2>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const createWorkspaceWorkspace2Response = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const createWorkspaceWorkspace2Request = z.lazy(() => {
  return z.object({ id: z.string().nullish(), name: z.string().nullish() }).transform((data) => ({
    id: data['id'],
    name: data['name'],
  }));
});
