// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import { globalVariable, globalVariableRequest, globalVariableResponse } from '../../common/global-variable';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getWorkspaceGlobalVariables = z.object({
  values: z.array(globalVariable).optional(),
});

/**
 * Information about the workspace's global variables.
 * @typedef  {GetWorkspaceGlobalVariables} getWorkspaceGlobalVariables - Information about the workspace's global variables. - Information about the workspace's global variables.
 * @property {GlobalVariable[]} - A list of the workspace's global variables.
 */
export type GetWorkspaceGlobalVariables = z.infer<typeof getWorkspaceGlobalVariables>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getWorkspaceGlobalVariablesResponse = z
  .object({
    values: z.array(globalVariableResponse).optional(),
  })
  .transform((data) => ({
    values: data['values'],
  }));

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getWorkspaceGlobalVariablesRequest = z
  .object({ values: z.array(globalVariableRequest).nullish() })
  .transform((data) => ({
    values: data['values'],
  }));
