// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';
import {
  getWorkspaceWorkspace,
  getWorkspaceWorkspaceRequest,
  getWorkspaceWorkspaceResponse,
} from './get-workspace-workspace';

/**
 * The shape of the model inside the application code - what the users use
 */
export const getWorkspace = z.lazy(() => {
  return z.object({
    workspace: getWorkspaceWorkspace.optional(),
  });
});

/**
 *
 * @typedef  {GetWorkspace} getWorkspace
 * @property {GetWorkspaceWorkspace} - Information about the workspace.
 */
export type GetWorkspace = z.infer<typeof getWorkspace>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const getWorkspaceResponse = z.lazy(() => {
  return z
    .object({
      workspace: getWorkspaceWorkspaceResponse.optional(),
    })
    .transform((data) => ({
      workspace: data['workspace'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const getWorkspaceRequest = z.lazy(() => {
  return z.object({ workspace: getWorkspaceWorkspaceRequest.nullish() }).transform((data) => ({
    workspace: data['workspace'],
  }));
});
