// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getWorkspacesInclude = z.enum(['mocks:deactivated']);

export type GetWorkspacesInclude = z.infer<typeof getWorkspacesInclude>;
