// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export enum WorkspaceType3 {
  PRIVATE_ = 'private',
  PERSONAL = 'personal',
  TEAM = 'team',
  PUBLIC_ = 'public',
}
