// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const workspaceType2 = z.enum(['personal', 'team', 'private', 'public', 'partner']);

export type WorkspaceType2 = z.infer<typeof workspaceType2>;
