// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

/**
 * The shape of the model inside the application code - what the users use
 */
export const workspaceApis: any = z.lazy(() => {
  return z.object({
    id: z.string().optional(),
    name: z.string().optional(),
    uid: z.string().optional(),
  });
});

/**
 * Information about the API.
 * @typedef  {WorkspaceApis} workspaceApis - Information about the API. - Information about the API.
 * @property {string} - The API's ID.
 * @property {string} - The API's name.
 * @property {string} - The API's unique ID.
 */
export type WorkspaceApis = z.infer<typeof workspaceApis>;

/**
 * The shape of the model mapping from the api schema into the application shape.
 * Is equal to application shape if all property names match the api schema
 */
export const workspaceApisResponse: any = z.lazy(() => {
  return z
    .object({
      id: z.string().optional(),
      name: z.string().optional(),
      uid: z.string().optional(),
    })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      uid: data['uid'],
    }));
});

/**
 * The shape of the model mapping from the application shape into the api schema.
 * Is equal to application shape if all property names match the api schema
 */
export const workspaceApisRequest: any = z.lazy(() => {
  return z
    .object({ id: z.string().nullish(), name: z.string().nullish(), uid: z.string().nullish() })
    .transform((data) => ({
      id: data['id'],
      name: data['name'],
      uid: data['uid'],
    }));
});
