// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const getAccountInvoicesStatus = z.enum(['PAID']);

export type GetAccountInvoicesStatus = z.infer<typeof getAccountInvoicesStatus>;
