// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const schemaLanguage = z.enum(['json', 'yaml']);

export type SchemaLanguage = z.infer<typeof schemaLanguage>;
