// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const dataResolution = z.enum(['FALSE_POSITIVE', 'ACCEPTED_RISK', 'REVOKED', 'ACTIVE']);

export type DataResolution = z.infer<typeof dataResolution>;
