// This file was generated by liblab | https://liblab.com/

import { z } from 'zod';

export const historyResolution = z.enum(['FALSE_POSITIVE', 'ACCEPTED_RISK', 'REVOKED', 'ACTIVE']);

export type HistoryResolution = z.infer<typeof historyResolution>;
