// This file was generated by liblab | https://liblab.com/

import { GetCollectionModel } from './models/get-collection-model';
import { AscDesc } from '../common/asc-desc';
import { Format } from './models/format';

export interface GetCollectionsParams {
  workspace?: string;
  name?: string;
}

export interface CreateCollectionParams {
  workspace?: string;
}

export interface CreateCollectionForkParams {
  workspace: string;
}

export interface GetCollectionParams {
  accessKey?: string;
  model?: GetCollectionModel;
}

export interface GetCollectionsForkedByUserParams {
  cursor?: string;
  limit?: number;
  direction?: AscDesc;
}

export interface GetCollectionForksParams {
  cursor?: string;
  limit?: number;
  direction?: AscDesc;
}

export interface TransformCollectionToOpenApiParams {
  format?: Format;
}
